const breakfast = [
    {
        id:1,
        Name:'Oatmeal-Almond Protein Pancakes',
        Time:'45 Min',
        Ingredients:'½ cup unflavored protein powder, ½ cup almond meal, ½ cup oat flour (see Tip), 1 tablespoon sugar, 1 teaspoon ground cinnamon, 1 teaspoon baking powder, ¼ teaspoon baking soda, ¼ teaspoon salt, 2 large eggs , ¾ cup buttermilk, 2 tablespoons canola oil, 2 teaspoons vanilla extract',
        StepOne:'Combine protein powder, almond meal, oat flour, sugar, cinnamon, baking powder, baking soda and salt in a blender; pulse until fully mixed. Add eggs, buttermilk (reduce to 1/2 cup if using whey protein), oil and vanilla; pulse, stopping to scrape down the sides as needed, until combined. Let stand for 15 minutes.',
        StepTwo:'Coat a large nonstick skillet or griddle with cooking spray; heat over medium-high heat',
        StepThree:'Make about 3 pancakes at a time, using 1/4 cup batter per pancake; reduce the heat to medium. Cook until the edges are dry, 1 to 3 minutes. Flip and cook until golden brown on the other side, 1 to 3 minutes more. Repeat with the remaining batter, using more cooking spray and reducing the heat as needed. Serve warm',
        Picture:'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F44%2F2019%2F08%2F26232437%2F3759134.jpg&q=60',
        type:'Breakfast',
    },
    {
        id:2,
        Name:'Sheet-Pan Egg Sandwiches',
        Time:'50 Min',
        Ingredients:'18 large eggs , ¼ cup reduced-fat milk, 1 tablespoon chili powder, 1 teaspoon onion powder, 1 teaspoon salt, 1 teaspoon ground pepper, ½ teaspoon ground cumin, 1 (10 ounce) package frozen chopped spinach, thawed and squeezed dry, 1 cup shredded extra-sharp Cheddar cheese, ¾ cup chopped red bell pepper, 4 slices cooked bacon, chopped (1/2 cup), 12 whole-wheat English muffins, toasted',
        StepOne:"Preheat oven to 300 degrees F. Generously coat a large (12-by-17-inch) rimmed baking sheet with cooking spray.",
        StepTwo:"Whisk eggs, milk, chili powder, onion powder, salt, pepper and cumin together in a large bowl. Pour onto the prepared baking sheet and sprinkle with spinach, cheese, bell pepper and bacon. Bake until just set, 22 to 28 minutes, rotating the pan from back to front halfway through to ensure even cooking.",
        StepThree:"Cut the eggs into 12 squares; sandwich each square in an English muffin",
        Picture:'https://food.fnr.sndimg.com/content/dam/images/food/fullset/2016/12/4/2/FNK_Sheet-Pan-Bacon-Egg-Sandwiches-for-a-Crowd_s4x3.jpg.rend.hgtvcom.616.462.suffix/1480899711403.jpeg',
        type:'Breakfast',
    },
    {
        id:3,
        Name:'Oatmeal with Cheddar, Collards & Eggs',
        Time:'25 Min',
        Ingredients:'2 tablespoons extra-virgin olive oil, divided, 2 tablespoons diced shallot, 2 cups rolled oats (see Tip), 4 cups water plus 1/2 cup, divided, ½ teaspoon salt, divided, ½ teaspoon ground pepper, divided, 10 cups chopped collard greens (from 1-2 bunches), 2 teaspoons red-wine vinegar, 1 cup shredded Cheddar cheese, ¼ cup chipotle salsa, plus more for serving, 4 large eggs, cooked as desired ',
        StepOne:'Heat 1 tablespoon oil in a large saucepan over medium heat. Add shallot and cook, stirring occasionally, until softened, 1 to 2 minutes. Add oats and stir for 1 minute. Add 4 cups water and 1/4 teaspoon each salt and pepper. Bring to a boil, then reduce heat to a simmer. Cook, stirring often, until creamy, 10 to 12 minutes.',
        StepTwo:'Meanwhile, heat the remaining 1 tablespoon oil in a large skillet over medium-high heat. Add collards along with the remaining 1/2 cup water and 1/4 teaspoon each salt and pepper. Cook, stirring occasionally, until tender, 5 to 7 minutes. Remove from heat and stir in vinegar.',
        StepThree:'Stir cheese and salsa into the oatmeal. Serve with the collards, eggs and more salsa, if desired.',
        Picture:'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F44%2F2019%2F08%2F26232315%2F5678186.jpg&q=60',
        type:'Breakfast',
    },
    {
        id:4,
        Name:'Egg in a Hole Peppers with Avocado Salsa',
        Time:'35 Min',
        Ingredients:'2 bell peppers, any color, 1 avocado, diced, ½ cup diced red onion , 1 jalapeño pepper, minced, ½ cup chopped fresh cilantro, plus more for garnish, 2 tomatoes, seeded and diced, Juice of 1 lime , ¾ teaspoon salt, divided2 teaspoons olive oil, divided, 8 large eggs , ¼ teaspoon ground pepper, divided',
        StepOne:'Slice tops and bottoms off bell peppers and finely dice. Remove and discard seeds and membranes. Slice each pepper into four 1/2-inch-thick rings.',
        StepTwo:'Combine the diced pepper with avocado, onion, jalapeño, cilantro, tomatoes, lime juice, and 1/2 teaspoon salt in a medium bowl.',
        StepThree:'Heat 1 teaspoon oil in a large nonstick skillet over medium heat. Add 4 bell pepper rings, then crack 1 egg into the middle of each ring. Season with 1/8 teaspoon each salt and pepper. Cook until the whites are mostly set but the yolks are still runny, 2 to 3 minutes. Gently flip and cook 1 minute more for runny yolks, 1 1/2 to 2 minutes more for firmer yolks. Transfer to serving plates and repeat with the remaining pepper rings and eggs.',
        Picture:'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F44%2F2019%2F08%2F26232307%2F5969602.jpg&q=60',
        type:'Breakfast',
    },
    {
        id:5,
        Name:'Cheesy Egg Quesadilla with Spinach',
        Time:'15 Min',
        Ingredients:'2 teaspoons extra-virgin olive oil, divided, 2 cups spinach, 2 corn tortillas, 4 tablespoons shredded Cheddar cheese, divided, 1 large egg , ¼ avocado, sliced, Hot sauce (optional)',
        StepOne:'Heat 1 teaspoon oil in a small nonstick skillet over medium-high heat. Add spinach and cook, stirring, until wilted, about 1 minute. Top 1 tortilla with 2 tablespoons cheese, the spinach and the remaining 2 tablespoons cheese. Cover with the other tortilla.',
        StepTwo:'Heat the remaining 1 teaspoon oil in the pan over medium-high heat. Add the quesadilla and cook, flipping once, until crispy, about 4 minutes. Transfer to a plate. Crack egg into the pan and cook until the white is set, about 4 minutes. Top the quesadilla with the egg and avocado.',
        StepThree:'Serve with hot sauce, if desired.',
        Picture:'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F44%2F2022%2F01%2F21%2Fsunny-side-up-quesadilla.jpg&q=60',
        type:'Breakfast',
    },
    {
        id:6,
        Name:'Breakfast Salad with Spinach & Egg',
        Time:'20 Min',
        Ingredients:'1 corn tortilla, 3 cups spinach, 1 tablespoon vinaigrette, 2 tablespoons shredded Cheddar cheese, 1 hard-boiled egg, sliced , ¼ avocado, diced',
        StepOne:'Preheat oven to 400°F. Place tortilla on a small baking sheet and bake, flipping once, until crunchy, about 8 minutes.',
        StepTwo:'Meanwhile, toss spinach with vinaigrette. Top with cheese, egg and avocado. Crumble the tortilla and sprinkle it on top of the salad',
        StepThree:'Serve with hot sauce, if desired.',
        Picture:'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F44%2F2022%2F02%2F07%2Fbreakfast-spinach-salad.jpg&q=60',
        type:'Breakfast',
    },
    {
        id:7,
        Name:'Protein Cereal',
        Time:'10 Min',
        Ingredients:'Any Cereal Of Choice, 1 Cup Milk, 1 Scoop Of Protein',
        StepOne:'Gather a bowl and poor your cereal of choice into it.',
        StepTwo:'Pour 1 cup Milk into your bowl',
        StepThree:'Add Protein Powder and Stir till it mixes in. Enjoy!',
        Picture:'https://brandsitesplatform-res.cloudinary.com/image/fetch/w_1500,c_scale,q_auto:eco,f_auto,fl_lossy,dpr_1.0,e_sharpen:85/https://assets.brandplatform.generalmills.com%2F-%2Fmedia%2FProject%2FGMI%2Fcorporate%2Fcorporate-master%2FImages%2FFood%2FProduct%2FWheaties-Jan-22.png%3Fw%3D2400%26rev%3Dc0f6b44ea7864ebc9410c0ebdc5ce081%201500w',
        type:'Breakfast',
    },
    {
        id:8,
        Name:'Chocolate-Banana Protein Smoothie',
        Time:'5-10 Min',
        Ingredients:'1 banana, frozen , ½ cup cooked red lentils, ½ cup nonfat milk, 2 teaspoons unsweetened cocoa powder, 1 teaspoon pure maple syrup',
        StepOne:'Combine All Ingredients Into Smoothie Cup.',
        StepTwo:'Start the blender and blend until Pure',
        StepThree:'Enjoy the Smoothie!',
        Picture:'https://www.acouplecooks.com/wp-content/uploads/2020/10/Chocolate-Banana-Spritzer-012.jpg',
        type:'Breakfast',
    },
    {
        id:9,
        Name:'Cauliflower Hash with Sausage & Eggs',
        Time:'25 Min',
        Ingredients:'4 teaspoons olive oil, divided, 1 small onion, diced , 2 cloves garlic, minced, 8 ounces turkey sausage, 16 ounces cauliflower rice (4 cups; see Tip), ¼ teaspoon salt, ⅛ teaspoon ground pepper, 3 tablespoons water, 8 large eggs',
        StepOne:'Heat 2 teaspoons oil in a large nonstick skillet over medium heat. Add onion and garlic; cook, stirring, until translucent. Add sausage; cook, stirring, until cooked through, 4 to 5 minutes. Transfer the mixture to a plate',
        StepTwo:'Increase heat to medium-high and add cauliflower rice to the pan in an even layer. Cook without stirring until it starts to turn golden brown, 2 to 3 minutes. Then stir and add salt, pepper, and water. Cover and cook until tender and golden, 3 to 4 minutes. Stir the sausage mixture back in and heat through, about 2 minutes.',
        StepThree:'Heat 1 teaspoon oil in a medium nonstick skillet over medium heat. Break 4 eggs into the pan and cook until the whites are set but the yolks are still runny, about 3 minutes (or up to 5 minutes for firmer yolks). Transfer to a plate and repeat with the remaining 1 teaspoon oil and the remaining 4 eggs',
        Picture:'https://static.onecms.io/wp-content/uploads/sites/44/2019/08/26232321/5959764.jpg',
        type:'Breakfast',
    }
]

export default breakfast